# Generated by Django 6.0 on 2026-01-26 00:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre completo', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ies')),
                ('acronym', models.CharField(max_length=50, unique=True, verbose_name='Siglas únicas')),
                ('year_start', models.IntegerField(blank=True, null=True)),
                ('year_end', models.IntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(blank=True, help_text='Es una institución pública?', null=True)),
            ],
            options={
                'verbose_name': 'Institución de Educación Superior',
                'verbose_name_plural': 'Instituciones de Educación Superior',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('year', models.IntegerField(help_text='Año', primary_key=True, serialize=False)),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Recuento de fechas')),
                ('good_practices_published', models.BooleanField(default=False, verbose_name='Buenas prácticas publicadas')),
                ('results_published', models.BooleanField(default=False, verbose_name='Resultados publicados')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
            },
        ),
        migrations.CreateModel(
            name='StatusControl',
            fields=[
                ('name', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('group', models.CharField(choices=[('register', 'Registro'), ('sending', 'Envío'), ('validation', 'Validación')], default='petition', max_length=10, verbose_name='grupo de status')),
                ('public_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, help_text='https://vuetifyjs.com/en/styles/colors/', max_length=30, null=True)),
                ('icon', models.CharField(blank=True, help_text='https://fonts.google.com/icons', max_length=40, null=True)),
                ('order', models.IntegerField(default=4)),
                ('is_final', models.BooleanField(default=False)),
                ('send_ies', models.BooleanField(default=False)),
                ('strict_ies', models.BooleanField(default=False)),
                ('send_admin', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('validator', 'Validador'), ('ies', 'Institución')], default='ies', max_length=10, verbose_name='rol asociado')),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Status de control',
                'verbose_name_plural': 'Status de control (TODOS)',
                'ordering': ['group', 'order'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('full_editor', models.BooleanField(default=False, help_text='Puede agregar notas, comentarios a los registros,pero no tiene todos los permisos', verbose_name='Es capturista')),
                ('mini_editor', models.BooleanField(default=False, help_text='Puede modificar ubicaciones y otros detalles', verbose_name='Servicio social')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='ies.institution')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
