# Generated by Django 6.0 on 2026-01-26 17:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_changed',
            field=models.BooleanField(default=False, verbose_name='Contraseña cambiada'),
        ),
        migrations.AlterField(
            model_name='period',
            name='year',
            field=models.IntegerField(editable=False, help_text='Año', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='InvitationToken',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha en que se vio')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha en que se usó')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ies.institution')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Invitación',
                'verbose_name_plural': 'Tokens de Invitación',
            },
        ),
    ]
