# Generated by Django 6.0.2 on 2026-02-25 23:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ies', '0002_user_password_changed_alter_period_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_editor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mini_editor',
        ),
        migrations.AddField(
            model_name='institution',
            name='is_centralized',
            field=models.BooleanField(blank=True, help_text='Gobierno centralizado', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reviewer',
            field=models.BooleanField(default=False, help_text='Puede verificar las respuestas y buenas prácticas', verbose_name='Es revisora'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='year_end',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2025), django.core.validators.MaxValueValidator(2040)]),
        ),
        migrations.AlterField(
            model_name='institution',
            name='year_start',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2025), django.core.validators.MaxValueValidator(2040)]),
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la instancia')),
                ('acronym', models.CharField(blank=True, max_length=50, null=True, verbose_name='Siglas de la instancia')),
                ('type_instance', models.CharField(choices=[('academic', 'Académica'), ('admin', 'Administrativa')], max_length=20, verbose_name='Tipo de instancia')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='ies.institution')),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
                'ordering': ['order'],
            },
        ),
    ]
