# Generated by Django 6.0.2 on 2026-02-27 21:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ies', '0003_remove_user_full_editor_remove_user_mini_editor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationtoken',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Es staff'),
        ),
        migrations.AddField(
            model_name='invitationtoken',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Es superusuario'),
        ),
        migrations.AddField(
            model_name='invitationtoken',
            name='reviewer',
            field=models.BooleanField(default=False, help_text='Solo aplica para invitaciones sin institución', verbose_name='Es revisora'),
        ),
        migrations.CreateModel(
            name='PasswordRecoveryToken',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha en que se usó')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Recuperación',
                'verbose_name_plural': 'Tokens de Recuperación',
                'ordering': ['-created_at'],
            },
        ),
    ]
