# Generated by Django 6.0.2 on 2026-03-02 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ies', '0004_invitationtoken_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationtoken',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_tokens', to='ies.institution'),
        ),
    ]
