# Generated by Django 6.0.2 on 2026-03-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ies', '0005_alter_invitationtoken_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationtoken',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='El correo fue enviado exitosamente', verbose_name='Correo enviado'),
        ),
    ]
