# Generated by Django 6.0 on 2026-01-10 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidences/')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('complement', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('reason_text', models.TextField(blank=True, null=True, verbose_name='Texto para justificar la calificación')),
                ('order', models.IntegerField(default=0)),
                ('is_other', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Característica a calificar',
                'verbose_name_plural': 'Características a calificar',
            },
        ),
        migrations.CreateModel(
            name='FeatureOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Opción de característica',
                'verbose_name_plural': 'Opciones de características',
                'ordering': ['feature__order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='GoodPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('results', models.TextField(blank=True, null=True)),
                ('final_value', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureGoodPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_attribute', models.BooleanField(default=False)),
                ('justification', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_practice_values', to='example.feature')),
            ],
        ),
    ]
