# Generated by Django 6.0 on 2026-01-26 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('example', '0001_initial'),
        ('ies', '0001_initial'),
        ('indicator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='featuregoodpractice',
            name='reviewers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidence',
            name='feature_good_practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='example.featuregoodpractice'),
        ),
        migrations.AddField(
            model_name='featureoption',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='example.feature'),
        ),
        migrations.AddField(
            model_name='featuregoodpractice',
            name='final_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='example.featureoption'),
        ),
        migrations.AddField(
            model_name='goodpractice',
            name='axis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='good_practices', to='indicator.axis'),
        ),
        migrations.AddField(
            model_name='goodpractice',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='good_practices', to='indicator.component'),
        ),
        migrations.AddField(
            model_name='goodpractice',
            name='status_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ies.statuscontrol'),
        ),
        migrations.AddField(
            model_name='featuregoodpractice',
            name='good_practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_values', to='example.goodpractice'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='good_practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='example.goodpractice'),
        ),
        migrations.AddField(
            model_name='goodpracticepackage',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='ies.institution'),
        ),
        migrations.AddField(
            model_name='goodpracticepackage',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='ies.period'),
        ),
        migrations.AddField(
            model_name='goodpracticepackage',
            name='status_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ies.statuscontrol'),
        ),
        migrations.AddField(
            model_name='goodpractice',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_practices', to='example.goodpracticepackage'),
        ),
    ]
