# Generated by Django 6.0 on 2026-01-12 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_initial'),
        ('ies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuregoodpractice',
            options={'verbose_name': 'Valor de Característica de Buena Práctica', 'verbose_name_plural': 'Valores de Características de Buenas Prácticas'},
        ),
        migrations.RemoveField(
            model_name='goodpractice',
            name='period',
        ),
        migrations.CreateModel(
            name='GoodPracticePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='ies.institution')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='ies.period')),
                ('status_sending', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ies.statuscontrol')),
            ],
            options={
                'verbose_name': 'Envío de Buenas Prácticas',
                'verbose_name_plural': 'Envío de Buenas Prácticas',
            },
        ),
        migrations.AddField(
            model_name='goodpractice',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='good_practices', to='example.goodpracticepackage'),
            preserve_default=False,
        ),
    ]
