# Generated by Django 6.0 on 2026-01-26 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodpracticepackage',
            options={'ordering': ['-period__year', 'institution__acronym'], 'verbose_name': 'Envío de Buenas Prácticas', 'verbose_name_plural': 'Envío de Buenas Prácticas'},
        ),
    ]
