# Generated by Django 6.0 on 2026-02-17 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_alter_goodpracticepackage_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodpractice',
            old_name='status_register',
            new_name='status_sending',
        ),
        migrations.RenameField(
            model_name='goodpracticepackage',
            old_name='status_register',
            new_name='status_sending',
        ),
    ]
