# Generated by Django 6.0 on 2026-01-18 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_alter_featuregoodpractice_options_and_more'),
        ('ies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodpractice',
            name='status_validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ies.statuscontrol'),
        ),
    ]
