# Generated by Django 6.0 on 2026-01-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_goodpractice_status_validation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodpractice',
            old_name='status_validation',
            new_name='status_register',
        ),
        migrations.RemoveField(
            model_name='featuregoodpractice',
            name='status_validation',
        ),
    ]
