# Generated by Django 6.0.2 on 2026-02-25 18:56

import django.db.models.deletion
from django.db import migrations, models


def set_survey_for_packages(apps, schema_editor):
    GoodPracticePackage = apps.get_model('example', 'GoodPracticePackage')
    Survey = apps.get_model('survey', 'Survey')

    for package in GoodPracticePackage.objects.filter(survey__isnull=True):
        survey = Survey.objects.filter(
            institution=package.institution, period=package.period).first()
        if survey:
            package.survey = survey
            package.save()


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_rename_status_register_goodpractice_status_sending_and_more'),
        ('survey', '0002_axisvalue_status_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodpracticepackage',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='survey.survey'),
        ),
        migrations.RunPython(set_survey_for_packages),
    ]
