# Generated by Django 6.0.2 on 2026-03-02 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_goodpracticepackage_survey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodpracticepackage',
            options={'ordering': ['-survey__period__year', 'survey__institution__acronym'], 'verbose_name': 'Envío de Buenas Prácticas', 'verbose_name_plural': 'Envío de Buenas Prácticas'},
        ),
        migrations.RemoveField(
            model_name='goodpracticepackage',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='goodpracticepackage',
            name='period',
        ),
    ]
