# Generated by Django 6.0 on 2026-01-21 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_rename_status_validation_goodpractice_status_register_and_more'),
        ('indicator', '0005_alter_axis_options_axis_short_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodpractice',
            options={'verbose_name': 'Buena Práctica', 'verbose_name_plural': 'Buenas Prácticas'},
        ),
        migrations.AlterField(
            model_name='featuregoodpractice',
            name='reviewers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='goodpractice',
            name='axis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='good_practices', to='indicator.axis'),
        ),
        migrations.AlterField(
            model_name='goodpractice',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='good_practices', to='indicator.component'),
        ),
    ]
