# Generated by Django 6.0 on 2026-01-21 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0006_alter_goodpractice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuregoodpractice',
            name='final_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='example.featureoption'),
        ),
    ]
