# Generated by Django 5.2.7 on 2025-10-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StairReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_identifiers', models.JSONField(blank=True, default=list, null=True, verbose_name='Todos los códigos identificadores')),
                ('route_start', models.CharField(blank=True, max_length=255, null=True, verbose_name='Inicio de la ruta')),
                ('path_start', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dónde inicia de escalera')),
                ('path_end', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dónde termina la escalera')),
                ('route_end', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fin de la ruta')),
                ('is_aligned', models.BooleanField(default=False, verbose_name='¿Está alineada con el ID')),
            ],
        ),
        migrations.CreateModel(
            name='StationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.DateTimeField(auto_now=True, verbose_name='Fecha/hora de reporte')),
                ('date_received', models.DateTimeField(auto_now=True, verbose_name='Fecha/hora de recepción')),
            ],
            options={
                'verbose_name': 'Reporte de estación',
                'verbose_name_plural': 'Reportes de estaciones',
            },
        ),
    ]
