# Generated by Django 5.2.7 on 2025-10-21 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report', '0001_initial'),
        ('stair', '0001_initial'),
        ('stop', '0003_alter_station_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stairreport',
            name='stair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stair.stair', verbose_name='Escalera reportada'),
        ),
        migrations.AddField(
            model_name='stationreport',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stop.station', verbose_name='Estación reportada'),
        ),
        migrations.AddField(
            model_name='stationreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
