# Generated by Django 5.2.7 on 2025-10-22 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stairreport',
            options={'verbose_name': 'Reporte de escalera', 'verbose_name_plural': 'Reportes de escaleras'},
        ),
        migrations.AddField(
            model_name='stairreport',
            name='date_received',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha/hora de recepción'),
        ),
        migrations.AddField(
            model_name='stairreport',
            name='date_reported',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha/hora de reporte'),
        ),
        migrations.AddField(
            model_name='stairreport',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles adicionales'),
        ),
        migrations.AddField(
            model_name='stairreport',
            name='is_working',
            field=models.BooleanField(default=False, verbose_name='¿Está funcionando?'),
        ),
        migrations.AddField(
            model_name='stairreport',
            name='other_status_maintenance',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro estado de mantenimiento'),
        ),
        migrations.AddField(
            model_name='stairreport',
            name='status_maintenance',
            field=models.CharField(blank=True, choices=[('full', 'En Reconstrucción'), ('medium', 'Mantenimiento Mayor (Tablas)'), ('minor', 'Mantenimiento Menor (Sin tablas)'), ('other', 'Otro tipo de mantenimiento')], max_length=10, null=True, verbose_name='Estado de mantenimiento'),
        ),
        migrations.AddField(
            model_name='stairreport',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EvidenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evidence_images/', verbose_name='Imagen de evidencia')),
                ('stair_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.stairreport', verbose_name='Reporte de escalera asociado')),
            ],
            options={
                'verbose_name': 'Imagen de evidencia',
                'verbose_name_plural': 'Imágenes de evidencia',
            },
        ),
        migrations.DeleteModel(
            name='StationReport',
        ),
    ]
