# Generated by Django 5.2.7 on 2025-10-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_stairreport_options_stairreport_date_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stairreport',
            name='direction_observed',
            field=models.CharField(blank=True, choices=[('up', 'Hacia arriba'), ('down', 'Hacia abajo')], max_length=10, null=True, verbose_name='Dirección observada'),
        ),
        migrations.AlterField(
            model_name='stairreport',
            name='is_working',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Está funcionando?'),
        ),
    ]
