# Generated by Django 5.2.7 on 2025-11-26 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_stairreport_direction_observed_and_more'),
        ('stair', '0002_stair_route_blur'),
    ]

    operations = [
        migrations.AddField(
            model_name='stairreport',
            name='is_accessible',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Es accesible?'),
        ),
        migrations.AddField(
            model_name='stairreport',
            name='same_end_as_route',
            field=models.BooleanField(default=False, verbose_name='¿Es el mismo punto que el destino?'),
        ),
        migrations.AddField(
            model_name='stairreport',
            name='same_start_as_route',
            field=models.BooleanField(default=False, verbose_name='¿Es el mismo punto que el origen?'),
        ),
        migrations.AlterField(
            model_name='evidenceimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='evidence_images/', verbose_name='Imagen de evidencia'),
        ),
        migrations.AlterField(
            model_name='evidenceimage',
            name='stair_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='report.stairreport', verbose_name='Reporte de escalera asociado'),
        ),
        migrations.AlterField(
            model_name='stairreport',
            name='stair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stair_reports', to='stair.stair', verbose_name='Escalera reportada'),
        ),
    ]
