# Generated by Django 6.0 on 2026-01-26 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Opción de respuesta de institucionalización',
                'verbose_name_plural': 'Opciones de respuesta de institucionalización',
            },
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('weight_name', models.CharField(max_length=40)),
                ('public_name', models.CharField(max_length=150)),
                ('model_question', models.CharField(blank=True, max_length=50, null=True)),
                ('default_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('model_response', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Grupo de preguntas',
                'verbose_name_plural': 'Grupos de preguntas',
            },
        ),
        migrations.CreateModel(
            name='AQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('observable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicator.observable')),
            ],
            options={
                'verbose_name': 'Pregunta de institucionalización',
                'verbose_name_plural': 'Preguntas de institucionalización',
            },
        ),
        migrations.CreateModel(
            name='BQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=10)),
                ('text', models.TextField()),
                ('includes_academic', models.BooleanField(blank=True, null=True, verbose_name='Incluye entidades académicas')),
                ('includes_admin', models.BooleanField(blank=True, null=True, verbose_name='Incluye dependencias administrativas')),
                ('observable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicator.observable')),
            ],
            options={
                'verbose_name': 'Pregunta de cuerpo',
                'verbose_name_plural': 'Preguntas de cuerpo',
            },
        ),
        migrations.CreateModel(
            name='PlanQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('observable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicator.observable')),
            ],
        ),
        migrations.CreateModel(
            name='ReachQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('has_main_sectors', models.BooleanField(default=True, verbose_name='Tiene los sectores principales')),
                ('has_general_planning', models.BooleanField(default=False, verbose_name='Tiene la opción de planeación general')),
                ('observable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicator.observable')),
                ('others_sectors', models.ManyToManyField(blank=True, to='indicator.sector')),
            ],
            options={
                'verbose_name': 'Pregunta de alcance de población',
                'verbose_name_plural': 'Preguntas de alcance de población',
            },
        ),
        migrations.CreateModel(
            name='SpecialQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('observable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicator.observable')),
            ],
            options={
                'verbose_name': 'Pregunta especial',
                'verbose_name_plural': 'Preguntas especiales',
            },
        ),
    ]
