# Generated by Django 6.0 on 2026-01-10 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Axis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.CharField(blank=True, max_length=55, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='axis_logos')),
                ('color', models.CharField(max_length=55)),
                ('hex_color', models.CharField(blank=True, max_length=7, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Materia (Axis)',
                'verbose_name_plural': 'Materias (Axes)',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('needs_name', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('is_main', models.BooleanField(default=True, verbose_name='Es sector principal')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicator.axis')),
            ],
        ),
        migrations.CreateModel(
            name='Observable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=2, max_digits=4)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('init_question', models.TextField(blank=True, null=True)),
                ('a_main_question', models.TextField(blank=True, null=True, verbose_name='Pregunta institucionalización')),
                ('a_main_subtitle', models.TextField(blank=True, null=True, verbose_name='Subtítulo institucionalización')),
                ('a_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ponderación institucionalización')),
                ('b_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ponderación cumplimiento')),
                ('reach_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ponderación alcance de población')),
                ('plan_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ponderación de planes')),
                ('special_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ponderación especial')),
                ('pop_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ponderación población')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicator.component')),
            ],
            options={
                'verbose_name': 'Observable',
                'verbose_name_plural': 'Observables',
            },
        ),
    ]
