# Generated by Django 6.0 on 2026-02-24 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['order'], 'verbose_name': 'Sector', 'verbose_name_plural': 'Sectores'},
        ),
    ]
