# Generated by Django 6.0 on 2026-01-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observable',
            name='a_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ponderación institucionalización'),
        ),
        migrations.AlterField(
            model_name='observable',
            name='b_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ponderación cumplimiento'),
        ),
        migrations.AlterField(
            model_name='observable',
            name='plan_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ponderación de planes'),
        ),
        migrations.AlterField(
            model_name='observable',
            name='pop_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ponderación población'),
        ),
        migrations.AlterField(
            model_name='observable',
            name='reach_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ponderación alcance de población'),
        ),
        migrations.AlterField(
            model_name='observable',
            name='special_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ponderación especial'),
        ),
    ]
