# Generated by Django 6.0.2 on 2026-02-25 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0002_alter_sector_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observable',
            options={'verbose_name': 'Observable (Pregunta inicial)', 'verbose_name_plural': 'Observables (Preguntas iniciales)'},
        ),
    ]
