# Generated by Django 6.0 on 2026-01-11 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0002_alter_observable_a_weight_alter_observable_b_weight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='axis',
            old_name='number',
            new_name='order',
        ),
    ]
