# Generated by Django 6.0 on 2026-01-11 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0003_rename_number_axis_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name': 'Componente', 'verbose_name_plural': 'Componentes'},
        ),
        migrations.RemoveField(
            model_name='axis',
            name='logo',
        ),
        migrations.AddField(
            model_name='axis',
            name='icon',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='observable',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observables', to='indicator.component'),
        ),
    ]
