# Generated by Django 6.0.2 on 2026-02-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0003_alter_observable_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralGroup',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('public_name', models.CharField(max_length=150)),
                ('fields', models.JSONField(blank=True, default=list)),
                ('is_population', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Grupo de preguntas (Generales)',
                'verbose_name_plural': 'Grupos de preguntas (Generales)',
            },
        ),
    ]
