# Generated by Django 6.0 on 2026-01-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0004_alter_component_options_remove_axis_logo_axis_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='axis',
            options={'ordering': ['order'], 'verbose_name': 'Materia (Axis)', 'verbose_name_plural': 'Materias (Axes)'},
        ),
        migrations.AddField(
            model_name='axis',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
