# Generated by Django 6.0 on 2026-01-26 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('snake_name', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del Modelo público (Meta.verbose_name_plural)', max_length=225, verbose_name='verbose_name_plural')),
                ('plural_name', models.CharField(max_length=225, verbose_name='Nombre plural')),
                ('model_name', models.CharField(help_text='Nombre del modelo en Django (Meta.model_name)', max_length=225, verbose_name='Nombre en Django')),
                ('app_label', models.CharField(default='null', max_length=40, verbose_name='App label')),
                ('order', models.SmallIntegerField(default=5, verbose_name='Orden')),
                ('icon', models.CharField(blank=True, max_length=225, null=True, verbose_name='Ícono')),
                ('color', models.CharField(blank=True, max_length=225, null=True, verbose_name='Color')),
                ('help_text', models.TextField(blank=True, null=True, verbose_name='Texto de ayuda')),
                ('fields', models.JSONField(default=list, verbose_name='Campos')),
                ('sort_fields', models.JSONField(blank=True, default=list, verbose_name='Campos de ordenamiento')),
                ('optional_category', models.BooleanField(default=False, verbose_name='Colección opcional')),
                ('all_filters', models.JSONField(default=list, verbose_name='Grupos de filtros')),
                ('open_insertion', models.BooleanField(blank=True, null=True)),
                ('xls_export', models.BooleanField(default=False, verbose_name='Tiene exportación a excel')),
                ('description', models.TextField(blank=True, null=True)),
                ('cat_params', models.JSONField(blank=True, default=dict, verbose_name='Parámetros para el catálogo')),
                ('available_actions', models.JSONField(default=list, verbose_name='Acciones disponibles')),
            ],
            options={
                'verbose_name': 'Modelo (Colección)',
                'verbose_name_plural': '1.1 Modelos (Colecciones)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('key_name', models.CharField(max_length=225, primary_key=True, serialize=False, verbose_name='Nombre')),
                ('name', models.CharField(max_length=225, verbose_name='Nombre público')),
                ('order', models.SmallIntegerField(default=5, verbose_name='Orden de aparición')),
            ],
            options={
                'verbose_name': 'Nivel de Colección',
                'verbose_name_plural': '1.3 Niveles de Colección',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FilterGroup',
            fields=[
                ('key_name', models.CharField(max_length=90, primary_key=True, serialize=False, verbose_name='Nombre')),
                ('name', models.CharField(max_length=225, verbose_name='Nombre público')),
                ('plural_name', models.CharField(max_length=225, verbose_name='Nombre plural')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('order', models.SmallIntegerField(default=5, verbose_name='Orden de aparición')),
                ('addl_config', models.JSONField(default=dict, verbose_name='Configuración adicional')),
                ('category_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_groups', to='ps_schema.collection')),
                ('category_subtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_subtypes', to='ps_schema.collection')),
                ('category_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_types', to='ps_schema.collection')),
            ],
            options={
                'verbose_name': 'Grupo de Filtros',
                'verbose_name_plural': '1.2 Grupos de Filtros',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps_schema.level', verbose_name='Nivel'),
        ),
    ]
