# Generated by Django 6.0 on 2026-01-26 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_instances_complying', models.IntegerField(blank=True, null=True)),
                ('admin_instances_complying', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Respuesta a pregunta B',
                'verbose_name_plural': 'Respuestas a preguntas B',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texto del comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comentario de encuesta',
                'verbose_name_plural': 'Comentarios de encuestas',
            },
        ),
        migrations.CreateModel(
            name='ObservableResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Respuesta observable',
                'verbose_name_plural': 'Respuestas observables',
            },
        ),
        migrations.CreateModel(
            name='PlanResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_plans', models.IntegerField(blank=True, null=True, verbose_name='Planes de nivel medio superior')),
                ('superior_plans', models.IntegerField(blank=True, null=True, verbose_name='Planes de nivel superior')),
                ('postgraduate_plans', models.IntegerField(blank=True, null=True, verbose_name='Planes de nivel posgrado')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje general')),
            ],
            options={
                'verbose_name': 'Respuesta a pregunta de Planes',
                'verbose_name_plural': 'Respuestas a preguntas de Planes',
            },
        ),
        migrations.CreateModel(
            name='ReachResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_focalized', models.BooleanField(default=False, verbose_name='No focalizado en sectores específicos')),
            ],
            options={
                'verbose_name': 'Respuesta de población',
                'verbose_name_plural': 'Respuestas de población',
            },
        ),
        migrations.CreateModel(
            name='ResponseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Comentario de encuesta',
                'verbose_name_plural': 'Comentarios de encuestas',
            },
        ),
        migrations.CreateModel(
            name='SpecialResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(blank=True, null=True)),
                ('complying', models.IntegerField(blank=True, null=True)),
                ('compliance_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Respuesta a pregunta especial',
                'verbose_name_plural': 'Respuestas a preguntas especiales',
            },
        ),
        migrations.CreateModel(
            name='AResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='question.aquestion')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_responses', to='question.aoption')),
            ],
            options={
                'verbose_name': 'Respuesta a pregunta A',
                'verbose_name_plural': 'Respuestas a preguntas A',
            },
        ),
    ]
