# Generated by Django 6.0.2 on 2026-02-25 23:59

import answer.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ies', '0003_remove_user_full_editor_remove_user_mini_editor_and_more'),
        ('indicator', '0004_generalgroup'),
        ('question', '0001_initial'),
        ('survey', '0003_survey_instances_survey_is_centralized_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_responses', to='question.questiontype')),
                ('status_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ies.statuscontrol')),
            ],
            options={
                'verbose_name': 'Grupo de Respuestas (por tipo)',
                'verbose_name_plural': 'Grupos de Respuestas (por tipo)',
            },
        ),
        migrations.CreateModel(
            name='GroupComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texto del comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ies.statuscontrol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='answer.groupresponse')),
            ],
            options={
                'verbose_name': 'Comentario de encuesta',
                'verbose_name_plural': 'Comentarios de encuestas',
            },
        ),
        migrations.CreateModel(
            name='GroupAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=answer.models.set_upload_attachment_path, verbose_name='Archivo')),
                ('group_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='answer.groupresponse')),
            ],
            options={
                'verbose_name': 'Comprobable de grupo de respuestas',
                'verbose_name_plural': 'Comprobables de grupos de respuestas',
            },
        ),
        migrations.CreateModel(
            name='BResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_instances_complying', models.IntegerField(blank=True, null=True)),
                ('admin_instances_complying', models.IntegerField(blank=True, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje general')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='question.bquestion')),
                ('group_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_responses', to='answer.groupresponse')),
            ],
            options={
                'verbose_name': 'Respuesta a pregunta B',
                'verbose_name_plural': 'Respuestas a preguntas B',
            },
        ),
        migrations.CreateModel(
            name='AResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='question.aquestion')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_responses', to='question.aoption')),
                ('group_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_responses', to='answer.groupresponse')),
            ],
            options={
                'verbose_name': 'Respuesta a pregunta A',
                'verbose_name_plural': 'Respuestas a preguntas A',
            },
        ),
        migrations.CreateModel(
            name='ObservableResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(blank=True, null=True, verbose_name='Respuesta a pregunta inicial')),
                ('observable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='indicator.observable')),
                ('status_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ies.statuscontrol')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observable_responses', to='survey.survey')),
            ],
            options={
                'verbose_name': 'Respuesta observable',
                'verbose_name_plural': 'Respuestas observables',
            },
        ),
        migrations.CreateModel(
            name='ObservableComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texto del comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ies.statuscontrol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('observable_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='answer.observableresponse')),
            ],
            options={
                'verbose_name': 'Comentario de respuesta observable',
                'verbose_name_plural': 'Comentarios de respuestas observables',
            },
        ),
        migrations.AddField(
            model_name='groupresponse',
            name='observable_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='answer.observableresponse'),
        ),
        migrations.CreateModel(
            name='PlanResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_plans', models.IntegerField(blank=True, null=True, verbose_name='Planes de nivel medio superior')),
                ('superior_plans', models.IntegerField(blank=True, null=True, verbose_name='Planes de nivel superior')),
                ('postgraduate_plans', models.IntegerField(blank=True, null=True, verbose_name='Planes de nivel posgrado')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje general')),
                ('group_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_responses', to='answer.groupresponse')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.planquestion')),
            ],
            options={
                'verbose_name': 'Respuesta a pregunta de Planes',
                'verbose_name_plural': 'Respuestas a preguntas de Planes',
            },
        ),
        migrations.CreateModel(
            name='ReachResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_focalized', models.BooleanField(default=False, verbose_name='No focalizado en sectores específicos')),
                ('group_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reach_responses', to='answer.groupresponse')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='question.reachquestion')),
                ('sectors', models.ManyToManyField(blank=True, related_name='reach_responses', to='indicator.sector')),
            ],
            options={
                'verbose_name': 'Respuesta de población',
                'verbose_name_plural': 'Respuestas de población',
            },
        ),
        migrations.CreateModel(
            name='SpecialResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(blank=True, null=True)),
                ('complying', models.IntegerField(blank=True, null=True)),
                ('compliance_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('group_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_responses', to='answer.groupresponse')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='question.specialquestion')),
            ],
            options={
                'verbose_name': 'Respuesta a pregunta especial',
                'verbose_name_plural': 'Respuestas a preguntas especiales',
            },
        ),
    ]
