# Generated by Django 6.0 on 2026-01-10 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('answer', '0001_initial'),
        ('ies', '0001_initial'),
        ('indicator', '0001_initial'),
        ('question', '0001_initial'),
        ('survey', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_question_responses', to='survey.survey'),
        ),
        migrations.AddField(
            model_name='bresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='question.bquestion'),
        ),
        migrations.AddField(
            model_name='bresponse',
            name='status_validation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_responses', to='ies.statuscontrol'),
        ),
        migrations.AddField(
            model_name='bresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_question_responses', to='survey.survey'),
        ),
        migrations.AddField(
            model_name='comment',
            name='question_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.questiongroup'),
        ),
        migrations.AddField(
            model_name='comment',
            name='status_validation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ies.statuscontrol'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observableresponse',
            name='observable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='indicator.observable'),
        ),
        migrations.AddField(
            model_name='observableresponse',
            name='status_validation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ies.statuscontrol'),
        ),
        migrations.AddField(
            model_name='observableresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observable_responses', to='survey.survey'),
        ),
        migrations.AddField(
            model_name='comment',
            name='observable_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='answer.observableresponse'),
        ),
        migrations.AddField(
            model_name='planresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.planquestion'),
        ),
        migrations.AddField(
            model_name='planresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey'),
        ),
        migrations.AddField(
            model_name='reachresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='question.reachquestion'),
        ),
        migrations.AddField(
            model_name='reachresponse',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='reach_responses', to='indicator.sector'),
        ),
        migrations.AddField(
            model_name='reachresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reach_responses', to='survey.survey'),
        ),
        migrations.AddField(
            model_name='specialresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='question.specialquestion'),
        ),
        migrations.AddField(
            model_name='specialresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_question_responses', to='survey.survey'),
        ),
    ]
