# Generated by Django 6.0 on 2026-01-18 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0002_initial'),
        ('ies', '0001_initial'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='status_validation',
            new_name='status_register',
        ),
        migrations.RenameField(
            model_name='observableresponse',
            old_name='status_validation',
            new_name='status_register',
        ),
        migrations.RemoveField(
            model_name='bresponse',
            name='status_validation',
        ),
        migrations.CreateModel(
            name='ResponseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observable_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='answer.observableresponse')),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.questiongroup')),
                ('status_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ies.statuscontrol')),
            ],
            options={
                'verbose_name': 'Comentario de encuesta',
                'verbose_name_plural': 'Comentarios de encuestas',
            },
        ),
    ]
