# Generated by Django 5.2.7 on 2025-10-21 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stop', '0003_alter_station_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField()),
                ('code_identifiers', models.JSONField(blank=True, default=list, null=True, verbose_name='Todos los códigos identificadores')),
                ('original_direction', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección según metro')),
                ('original_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación según metro')),
                ('validated', models.BooleanField(default=False)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stairs', to='stop.stop', verbose_name='Estación (stop)')),
            ],
            options={
                'verbose_name': 'Escalera',
                'verbose_name_plural': 'Escaleras',
            },
        ),
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathway_id', models.CharField(db_index=True, help_text='Identifies a pathway', max_length=255, unique=True)),
                ('pathway_mode', models.IntegerField(choices=[(1, 'Walkway'), (2, 'Stairs'), (3, 'Moving sidewalk/travelator'), (4, 'Escalator'), (5, 'Elevator'), (6, 'Fare gate'), (7, 'Exit gate')])),
                ('is_bidirectional', models.IntegerField(choices=[(0, 'Unidirectional'), (1, 'Bidirectional')], help_text='0=Unidirectional (from→to only), 1=Bidirectional')),
                ('length', models.FloatField(blank=True, help_text='Horizontal length in meters of the pathway', null=True)),
                ('traversal_time', models.PositiveIntegerField(blank=True, help_text='Average time in seconds needed to walk through the pathway', null=True)),
                ('stair_count', models.IntegerField(blank=True, help_text='Number of stairs (positive=up, negative=down from from_stop to to_stop)', null=True)),
                ('max_slope', models.FloatField(blank=True, help_text='Maximum slope ratio (positive=upwards, negative=downwards)', null=True)),
                ('min_width', models.FloatField(blank=True, help_text='Minimum width of the pathway in meters', null=True)),
                ('signposted_as', models.TextField(blank=True, help_text='Public facing text from physical signage visible to riders', null=True)),
                ('reversed_signposted_as', models.TextField(blank=True, help_text='Signage text when pathway is used from to_stop to from_stop', null=True)),
                ('from_stop', models.ForeignKey(db_column='from_stop_id', help_text='Location at which the pathway begins', on_delete=django.db.models.deletion.CASCADE, related_name='pathways_from', to='stop.stop')),
                ('to_stop', models.ForeignKey(db_column='to_stop_id', help_text='Location at which the pathway ends', on_delete=django.db.models.deletion.CASCADE, related_name='pathways_to', to='stop.stop')),
            ],
            options={
                'verbose_name': 'Pathway',
                'verbose_name_plural': 'Pathways',
                'indexes': [models.Index(fields=['from_stop'], name='stair_pathw_from_st_31c318_idx'), models.Index(fields=['to_stop'], name='stair_pathw_to_stop_a4bc96_idx'), models.Index(fields=['pathway_mode'], name='stair_pathw_pathway_77daeb_idx')],
            },
        ),
    ]
