# Generated by Django 5.2.7 on 2025-11-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stair', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stair',
            name='route_blur',
            field=models.BooleanField(default=False, verbose_name='Línea poco clara'),
        ),
    ]
