# Generated by Django 6.0.2 on 2026-02-25 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook / Microsoft 365'), ('custom', 'Personalizado')], default='gmail', max_length=20)),
                ('host', models.CharField(blank=True, help_text='Vacío = usar preset del proveedor', max_length=200)),
                ('port', models.IntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('username', models.EmailField(max_length=254)),
                ('password_env_var', models.CharField(help_text='Nombre de la variable de entorno que contiene la contraseña/app token', max_length=100)),
                ('from_email', models.EmailField(blank=True, help_text='Vacío = usar username como remitente', max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Perfil usado cuando el template no especifica uno')),
            ],
            options={
                'verbose_name': 'Perfil de correo',
                'verbose_name_plural': 'Perfiles de correo',
            },
        ),
        migrations.CreateModel(
            name='TemplateBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ruta del template relativa a templates/ (ej: email/invitation.html)', max_length=200, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('from_name', models.CharField(blank=True, help_text='Sobrescribe el from_name del perfil para este template', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, help_text='Vacío = usar el perfil default activo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='email_send.emailprofile')),
            ],
            options={
                'verbose_name': 'Template de correo',
                'verbose_name_plural': 'Templates de correo',
            },
        ),
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('context_data', models.JSONField(blank=True, help_text='Contexto serializable usado para renderizar', null=True)),
                ('send_email', models.BooleanField(default=False, help_text='¿Se intentó enviar el correo?')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('errors', models.JSONField(blank=True, null=True)),
                ('message_id', models.CharField(blank=True, help_text='ID retornado por el servidor SMTP', max_length=200, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='email_send.emailprofile')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que disparó el envío', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_records', to=settings.AUTH_USER_MODEL)),
                ('template_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='email_send.templatebase')),
            ],
            options={
                'verbose_name': 'Registro de correo',
                'verbose_name_plural': 'Registros de correos',
                'ordering': ['-created'],
            },
        ),
    ]
