# Generated by Django 6.0 on 2026-01-10 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ies', '0001_initial'),
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_instances', models.IntegerField(verbose_name='Instancias académicas')),
                ('admin_instances', models.IntegerField(verbose_name='Instancias administrativas')),
                ('media_plans', models.IntegerField(verbose_name='Planes a nivel medio superior')),
                ('superior_plans', models.IntegerField(verbose_name='Planes a nivel superior')),
                ('postgraduate_plans', models.IntegerField(verbose_name='Planes a nivel posgrado')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='ies.institution')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='ies.period')),
                ('sectors', models.ManyToManyField(related_name='surveys', to='indicator.sector', verbose_name='Sectores atendidos')),
            ],
            options={
                'verbose_name': 'Conjunto de respuestas IES-Año',
                'verbose_name_plural': 'Conjuntos de respuestas IES-Año',
                'unique_together': {('institution', 'period')},
            },
        ),
        migrations.CreateModel(
            name='PopulationQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_apply', models.BooleanField(default=False, verbose_name='No Aplica')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del sector')),
                ('number_men', models.PositiveIntegerField(verbose_name='Número de hombres')),
                ('number_women', models.PositiveIntegerField(verbose_name='Número de mujeres')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='population_quantities', to='indicator.sector')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='population_quantities', to='survey.survey')),
            ],
            options={
                'verbose_name': 'Cantidad de población por sector',
                'verbose_name_plural': 'Cantidades de población por sector',
            },
        ),
        migrations.CreateModel(
            name='ComponentValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_values', to='indicator.component')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_values', to='survey.survey')),
            ],
            options={
                'verbose_name': 'Valor del componente',
                'verbose_name_plural': 'Valores de los componentes',
            },
        ),
        migrations.CreateModel(
            name='AxisValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axis_values', to='indicator.axis')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axis_values', to='survey.survey')),
            ],
            options={
                'verbose_name': 'Valor del eje',
                'verbose_name_plural': 'Valores de los ejes',
            },
        ),
    ]
