# Generated by Django 6.0 on 2026-02-17 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ies', '0002_user_password_changed_alter_period_year_and_more'),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='axisvalue',
            name='status_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ies.statuscontrol'),
        ),
    ]
