# Generated by Django 6.0 on 2026-01-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='academic_instances',
            field=models.IntegerField(blank=True, null=True, verbose_name='Instancias académicas'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='admin_instances',
            field=models.IntegerField(blank=True, null=True, verbose_name='Instancias administrativas'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='media_plans',
            field=models.IntegerField(blank=True, null=True, verbose_name='Planes a nivel medio superior'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='postgraduate_plans',
            field=models.IntegerField(blank=True, null=True, verbose_name='Planes a nivel posgrado'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='superior_plans',
            field=models.IntegerField(blank=True, null=True, verbose_name='Planes a nivel superior'),
        ),
    ]
