# Generated by Django 6.0.2 on 2026-02-25 23:59

import django.db.models.deletion
import survey.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ies', '0003_remove_user_full_editor_remove_user_mini_editor_and_more'),
        ('indicator', '0004_generalgroup'),
        ('survey', '0002_axisvalue_status_register'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='instances',
            field=models.ManyToManyField(blank=True, related_name='surveys', to='ies.instance', verbose_name='Instancias'),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_centralized',
            field=models.BooleanField(blank=True, help_text='Gobierno centralizado', null=True),
        ),
        migrations.CreateModel(
            name='GeneralGroupResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_group_responses', to='indicator.generalgroup')),
                ('status_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ies.statuscontrol')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_group_responses', to='survey.survey')),
            ],
            options={
                'verbose_name': 'Grupo de Respuestas General',
                'verbose_name_plural': 'Grupos de Respuestas Generales',
            },
        ),
        migrations.CreateModel(
            name='GeneralGroupComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texto del comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ies.statuscontrol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('general_group_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='survey.generalgroupresponse')),
            ],
            options={
                'verbose_name': 'Comentario a grupo de respuestas (General)',
                'verbose_name_plural': 'Comentarios a grupos de respuestas (General)',
            },
        ),
        migrations.CreateModel(
            name='GeneralGroupAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=survey.models.set_upload_general_attachment_path, verbose_name='Archivo')),
                ('general_group_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='survey.generalgroupresponse')),
            ],
            options={
                'verbose_name': 'Comprobable de grupo general de respuestas',
                'verbose_name_plural': 'Comprobables de grupos generales de respuestas',
            },
        ),
    ]
