# Generated by Django 6.0 on 2026-01-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0005_alter_axis_options_axis_short_name'),
        ('survey', '0002_alter_survey_academic_instances_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='surveys', to='indicator.sector', verbose_name='Sectores atendidos'),
        ),
    ]
