# Generated by Django 6.0.2 on 2026-03-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_survey_instances_survey_is_centralized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populationquantity',
            name='number_men',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de hombres'),
        ),
        migrations.AlterField(
            model_name='populationquantity',
            name='number_women',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de mujeres'),
        ),
    ]
