# Generated by Django 5.2.7 on 2025-10-21 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(db_index=True, help_text='Identifies a route', max_length=255, unique=True)),
                ('route_short_name', models.CharField(blank=True, help_text="Short name of a route (e.g., '32', '100X', 'Green')", max_length=50, null=True, verbose_name='Nombre corto')),
                ('route_long_name', models.CharField(blank=True, help_text='Full name of a route', max_length=255, null=True, verbose_name='Nombre largo')),
                ('route_desc', models.TextField(blank=True, help_text='Description of a route that provides useful,quality information', null=True, verbose_name='Descripción')),
                ('route_type', models.IntegerField(choices=[(0, 'Tram, Streetcar, Light rail'), (1, 'Subway, Metro'), (2, 'Rail'), (3, 'Bus'), (4, 'Ferry'), (5, 'Cable tram'), (6, 'Aerial lift, suspended cable car'), (7, 'Funicular'), (11, 'Trolleybus'), (12, 'Monorail')], default=1, help_text='Indicates the type of transportation used on a route')),
                ('route_url', models.URLField(blank=True, help_text='URL of a web page about the particular route', null=True, verbose_name='URL')),
                ('route_color', models.CharField(blank=True, default='FFFFFF', help_text='Route color designation (hex color without #)', max_length=6, null=True)),
                ('route_text_color', models.CharField(blank=True, default='000000', help_text='Legible color to use for text drawn against route_color', max_length=6, null=True)),
                ('route_sort_order', models.PositiveIntegerField(blank=True, help_text='Orders the routes for presentation to customers', null=True)),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'db_table': 'routes',
                'indexes': [models.Index(fields=['route_type'], name='routes_route_t_6c43ff_idx'), models.Index(fields=['route_short_name'], name='routes_route_s_66fa4a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.CharField(db_index=True, max_length=255)),
                ('shape_pt_lat', models.DecimalField(decimal_places=6, help_text='Latitude of a shape point', max_digits=9, verbose_name='Latitud del punto')),
                ('shape_pt_lon', models.DecimalField(decimal_places=6, help_text='Longitude of a shape point', max_digits=9, verbose_name='Longitud del punto')),
                ('shape_pt_sequence', models.PositiveIntegerField(help_text='Sequence in which the shape points connect to form the shape', verbose_name='Secuencia del punto')),
                ('shape_dist_traveled', models.FloatField(blank=True, help_text='Actual distance traveled along the shape from the first shape point', null=True, verbose_name='Distancia recorrida')),
            ],
            options={
                'verbose_name': 'Shape',
                'verbose_name_plural': 'Shapes',
                'db_table': 'shapes',
                'ordering': ['shape_id', 'shape_pt_sequence'],
                'indexes': [models.Index(fields=['shape_id', 'shape_pt_sequence'], name='shapes_shape_i_e65d2f_idx')],
                'unique_together': {('shape_id', 'shape_pt_sequence')},
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('viz_params', models.JSONField(blank=True, default=dict, null=True)),
                ('main_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_stations', to='stop.route')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(db_index=True, help_text='Identifies a location: stop/platform, station, entrance/exit, generic node or boarding area', max_length=255, unique=True)),
                ('stop_code', models.CharField(blank=True, help_text='Short text or number that identifies the location for riders', max_length=50, null=True, verbose_name='Código')),
                ('stop_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('stop_desc', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('stop_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('stop_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('location_type', models.IntegerField(blank=True, choices=[(0, 'Stop/Platform'), (1, 'Station'), (2, 'Entrance/Exit'), (3, 'Generic Node'), (4, 'Boarding Area')], default=0, help_text='Location type', null=True)),
                ('wheelchair_boarding', models.IntegerField(blank=True, choices=[(0, 'No accessibility information'), (1, 'Wheelchair accessible'), (2, 'Not wheelchair accessible')], default=0, help_text='Indicates whether wheelchair boardings are possible', null=True)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='stop.station')),
            ],
            options={
                'verbose_name': 'Stop',
                'verbose_name_plural': 'Stops',
                'db_table': 'stops',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('trip_headsign', models.CharField(blank=True, help_text="Text that appears on signage identifying the trip's destination", max_length=255, null=True, verbose_name='Headsign')),
                ('trip_short_name', models.CharField(blank=True, help_text='Public facing text used to identify the trip to riders', max_length=50, null=True, verbose_name='Nombre corto del viaje')),
                ('direction_id', models.IntegerField(blank=True, choices=[(0, 'Outbound travel'), (1, 'Inbound travel')], help_text='Indicates the direction of travel for a trip', null=True)),
                ('shape_id', models.CharField(blank=True, help_text='Identifies a geospatial shape describing the vehicle travel path', max_length=255, null=True)),
                ('wheelchair_accessible', models.IntegerField(blank=True, choices=[(0, 'No accessibility information'), (1, 'Vehicle can accommodate at least one wheelchair'), (2, 'No wheelchairs can be accommodated')], default=0, help_text='Indicates wheelchair accessibility', null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='stop.route', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'db_table': 'trips',
            },
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField(blank=True, help_text='Arrival time at the stop for a specific trip (format: HH:MM:SS)', null=True, verbose_name='Hora de llegada')),
                ('departure_time', models.TimeField(blank=True, help_text='Departure time from the stop for a specific trip (format: HH:MM:SS)', null=True, verbose_name='Hora de salida')),
                ('timepoint', models.IntegerField(blank=True, choices=[(0, 'Times are considered approximate'), (1, 'Times are considered exact')], default=1, help_text='Indicates if times are strictly adhered to or approximate', null=True)),
                ('stop_sequence', models.PositiveIntegerField(help_text='Order of stops for a particular trip')),
                ('stop', models.ForeignKey(blank=True, help_text='Identifies the serviced stop', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='stop.stop')),
                ('trip', models.ForeignKey(help_text='Identifies a trip', on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='stop.trip')),
            ],
            options={
                'verbose_name': 'Stop Time',
                'verbose_name_plural': 'Stop Times',
                'db_table': 'stop_times',
                'ordering': ['trip', 'stop_sequence'],
                'indexes': [models.Index(fields=['trip', 'stop_sequence'], name='stop_times_trip_id_fe5890_idx'), models.Index(fields=['stop'], name='stop_times_stop_id_286e85_idx'), models.Index(fields=['arrival_time'], name='stop_times_arrival_4d5385_idx'), models.Index(fields=['departure_time'], name='stop_times_departu_a25773_idx')],
                'unique_together': {('trip', 'stop_sequence')},
            },
        ),
    ]
