# Generated by Django 5.2.7 on 2025-10-21 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='route',
            field=models.ForeignKey(blank=True, help_text='Ruta principal (solo METRO CDMX)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='stop.route'),
        ),
        migrations.AddField(
            model_name='stop',
            name='zone_id',
            field=models.CharField(blank=True, help_text='Identifies the fare zone for a stop', max_length=255, null=True),
        ),
    ]
