# Generated by Django 5.2.7 on 2025-10-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stop', '0002_stop_route_stop_zone_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': 'Station', 'verbose_name_plural': 'Stations'},
        ),
        migrations.RenameIndex(
            model_name='route',
            new_name='stop_route_route_t_1e6194_idx',
            old_name='routes_route_t_6c43ff_idx',
        ),
        migrations.RenameIndex(
            model_name='route',
            new_name='stop_route_route_s_25c6cd_idx',
            old_name='routes_route_s_66fa4a_idx',
        ),
        migrations.RenameIndex(
            model_name='shape',
            new_name='stop_shape_shape_i_6c8c71_idx',
            old_name='shapes_shape_i_e65d2f_idx',
        ),
        migrations.RenameIndex(
            model_name='stoptime',
            new_name='stop_stopti_trip_id_294a2e_idx',
            old_name='stop_times_trip_id_fe5890_idx',
        ),
        migrations.RenameIndex(
            model_name='stoptime',
            new_name='stop_stopti_stop_id_f3284f_idx',
            old_name='stop_times_stop_id_286e85_idx',
        ),
        migrations.RenameIndex(
            model_name='stoptime',
            new_name='stop_stopti_arrival_03e89e_idx',
            old_name='stop_times_arrival_4d5385_idx',
        ),
        migrations.RenameIndex(
            model_name='stoptime',
            new_name='stop_stopti_departu_c44dd0_idx',
            old_name='stop_times_departu_a25773_idx',
        ),
        migrations.AddField(
            model_name='station',
            name='end_anchor',
            field=models.BooleanField(default=False, help_text='Indicates if the station is an end anchor of a route'),
        ),
        migrations.AddField(
            model_name='station',
            name='rotation',
            field=models.SmallIntegerField(blank=True, help_text='Rotation angle for visualization purposes', null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='x_position',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Posición X'),
        ),
        migrations.AddField(
            model_name='station',
            name='y_position',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Posición Y'),
        ),
        migrations.AlterModelTable(
            name='route',
            table=None,
        ),
        migrations.AlterModelTable(
            name='shape',
            table=None,
        ),
        migrations.AlterModelTable(
            name='stop',
            table=None,
        ),
        migrations.AlterModelTable(
            name='stoptime',
            table=None,
        ),
        migrations.AlterModelTable(
            name='trip',
            table=None,
        ),
    ]
