# Generated by Django 5.2.7 on 2025-10-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stop', '0003_alter_station_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='end_anchor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='rotation',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
