# Generated by Django 5.2.7 on 2025-11-10 15:42

from django.db import migrations, models


def edit_created_stops(apps, schema_editor):
    # from stop.models import Stop
    Stop = apps.get_model('stop', 'Stop')
    Stop.objects.filter(location_type=0).update(location_type=1)


class Migration(migrations.Migration):

    dependencies = [
        ('stop', '0004_alter_station_end_anchor_alter_station_rotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='location_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Stop/Platform'), (1, 'Station'), (2, 'Entrance/Exit'), (3, 'Generic Node'), (4, 'Boarding Area')], help_text='Location type', null=True),
        ),
        migrations.RunPython(edit_created_stops),
    ]
